# Generated by Django 4.1.4 on 2023-04-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_review_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="movies.actor"),
        ),
    ]
